#pragma once

#include "ItemTemplate.h"

#include <memory>
#include <string_view>

/** Built-in DataTemplate contract used by GroupStyle.HeaderTemplate. */
inline constexpr std::wstring_view CollectionViewGroupDataTypeName =
	L"CollectionViewGroup";

/** Visual policy for headers generated by a grouped ItemsSource. */
struct GroupStyle final
{
	ItemTemplateReference HeaderTemplate;
	float HeaderIndent = 16.0f;
	float HeaderSpacing = 4.0f;
	/** Exact per-header extent used by grouped virtualizing panels. */
	float HeaderHeight = 24.0f;
};

class GroupStyleReference final
{
public:
	GroupStyleReference() = default;
	explicit GroupStyleReference(std::shared_ptr<const GroupStyle> value)
		: _value(std::move(value)) {}

	const GroupStyle* Get() const noexcept { return _value.get(); }
	const std::shared_ptr<const GroupStyle>& Shared() const noexcept
	{
		return _value;
	}
	explicit operator bool() const noexcept { return static_cast<bool>(_value); }
	bool operator==(const GroupStyleReference& other) const noexcept
	{
		return _value == other._value;
	}

private:
	std::shared_ptr<const GroupStyle> _value;
};
