#pragma once

#include "ListBox.h"

/** WPF-style item container generated by ListView. */
class ListViewItem final : public ListBoxItem
{
public:
	ListViewItem() = default;
	UIClass Type() override { return UIClass::UI_ListViewItem; }
	static void RegisterDependencyProperties();
	void EnsureBindingPropertiesRegistered() override
	{
		RegisterDependencyProperties();
	}
};

/**
 * WPF-style ListView.
 *
 * ListView is a ListBox specialization. Items, ItemsSource, selection,
 * templates, containers, scrolling and virtualization therefore use the one
 * ItemsControl/Selector pipeline instead of a second immediate-mode list
 * implementation.
 */
class ListView final : public ListBox
{
public:
	ListView();
	UIClass Type() override { return UIClass::UI_ListView; }
	static void RegisterDependencyProperties();
	void EnsureBindingPropertiesRegistered() override
	{
		RegisterDependencyProperties();
	}

protected:
	std::unique_ptr<Control> BuildGeneratedItem(
		const BindingSourceReference& item,
		size_t index,
		BindingPathObservation& observation) override;
};
